name: HyacinthHello
description: '${project.version}'
version: '${project.version}'
main: site.remlit.blueb.hyacinthhello.HyacinthHelloOld
api-version: 1.19
authors: [ blueb ]
softdepend: [ PlaceholderAPI ]
commands:
  joinmsg:
    description: Set a custom join message
    usage: /joinmsg [message]
    permission: hyacinthhello.joinmessage
    permission-message: You don't have hyacinthhello.joinmessage!
    aliases: [joinmessage]
  leavemsg:
    description: Set a custom leave message
    usage: /leavemsg [message]
    permission: hyacinthhello.leavemessage
    permission-message: You don't have hyacinthhello.leavemessage!
    aliases: [quitmsg, leavemessage, quitmessage]
  deathmsg:
    description: Set a custom death message
    usage: /deathmsg [message]
    permission: hyacinthhello.deathmessage
    permission-message: You don't have hyacinthhello.deathmessage!
    aliases: [deathmessage]
  hyacinthhello:
    description: Commands related to HyacinthHello
    usage: /hyacinthhello
    permission: hyacinthhello.command
    permission-message: You don't have hyacinthhello.command!
    aliases: [hyacinth, hh]